# Generated by Django 3.2.15 on 2023-03-02 18:58

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_item_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='', verbose_name='Главное изображение'),
        ),
    ]
