# Generated by Django 3.2.15 on 2023-03-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20230302_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='main_image',
        ),
    ]
