# Generated by Django 3.2.15 on 2023-03-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_item_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='main_image2',
            new_name='main_image',
        ),
    ]
