# Generated by Django 3.2.15 on 2023-03-03 12:16

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20230303_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoforgallery',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='media', verbose_name='Изображение'),
        ),
    ]
