# Generated by Django 3.2.15 on 2023-03-04 15:27

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_photoforgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Укажите слаг', max_length=200, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100, help_text='Чем меньше вес, тем раньше товар в выдаче', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)], verbose_name='вес'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='item_connected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='главное изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Укажите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите тэги.', to='catalog.Tag', verbose_name='тэги'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Укажите описание товара', validators=[core.validators.validator_word_good], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='photoforgallery',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='photoforgallery',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Укажите слаг', max_length=200, unique=True, verbose_name='слаг'),
        ),
    ]
