# Generated by Django 3.2.15 on 2023-03-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_imagemodel_item_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_om_main',
            field=models.BooleanField(default=False, help_text='Укажите, должен ли товар отображаться на главной', verbose_name='отображать товар на главной?'),
        ),
    ]
