# Generated by Django 3.2.15 on 2023-03-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_item_is_om_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_om_main',
            new_name='is_on_main',
        ),
    ]
