# Generated by Django 3.2.15 on 2023-03-23 20:06

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='coffee_count',
            field=models.IntegerField(default=0, verbose_name='количество попыток сварить кофе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='user_pics/', verbose_name='аватарка'),
        ),
    ]
